name: Artifact vs Output Comparison
on: [ workflow_dispatch ]
jobs:
    seller:
        runs-on: ubuntu-latest
        outputs:
            selling_price: ${{ steps.price_id.outputs.price }}
        steps: 
            - name: Creating a a file for using it as artifactory
              run: echo "Hello Smriti" >> test.txt
            - name: Setting a output that can be used in another job
              id: price_id
              run: echo "price=The price is 100" >> $GITHUB_OUTPUT
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: testArtifact
                path: test.txt
    
    buyer:
        runs-on: ubuntu-latest
        needs: seller
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: testArtifact
            - name: Print the present working directory
              run: pwd
            - name: List out the files
              run: ls -lrth
            - name: Print file content
              run: cat test.txt
            - name: Print the output from the previous job
              run: echo "The selling price is ${{ needs.seller.outputs.selling_price }}"
    
