name: Testing if cache works in diff workflow

on: 
  workflow_dispatch:   # Manual trigger

jobs:
  testing-cache-from-diff-workflow:   # Job name without spaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore Node.js modules cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Output contents
        run: ls -lrth

      - name: Deploy
        run: echo "Deploying..."  # Placeholder for deployment
